// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePerson = "person"

// Person mapped from table <person>
type Person struct {
	ID       int64  `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id"`
	UserName string `gorm:"column:user_name;type:varchar(128)" json:"user_name"`
	PassWord string `gorm:"column:pass_word;type:varchar(45)" json:"pass_word"`
	RealName string `gorm:"column:real_name;type:varchar(128)" json:"real_name"`
	Version  int32  `gorm:"column:version;type:int(10) unsigned;not null;default:1" json:"version"`
}

// TableName Person's table name
func (*Person) TableName() string {
	return TableNamePerson
}
