// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

//CREATE TABLE `person` (
//  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
//  `user_name` varchar(128) DEFAULT NULL,
//  `pass_word` varchar(45) DEFAULT NULL,
//  `real_name` varchar(128) DEFAULT NULL,
//  `version` int(10) unsigned NOT NULL DEFAULT '1',
//  PRIMARY KEY (`id`),
//  KEY `idx_name` (`user_name`)
//) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4

const TableNamePerson = "person"

// Person mapped from table <person>
type Person struct {
	ID       int64  `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"id"`
	UserName string `gorm:"column:user_name;type:varchar(128)" json:"user_name"`
	PassWord string `gorm:"column:pass_word;type:varchar(45)" json:"pass_word"`
	RealName string `gorm:"column:real_name;type:varchar(128)" json:"real_name"`
	Version  int32  `gorm:"column:version;type:int(10) unsigned;not null;default:1" json:"version"`
}

// TableName Person's table name
func (*Person) TableName() string {
	return TableNamePerson
}
